@startuml
[*] --> Propuesto
Propuesto --> EnRevisión : Proponer curso
state c <<choice>>
EnRevisión --> c : ¿Aprobado? 
c --> Cancelado : [No] 
c --> Aprobado : [Si]
Aprobado --> EnEjecución: Ejecutar curso
EnEjecución --> Finalizado : Finalizar curso
EnEjecución --> Cancelado : Cancelar curso
Finalizado --> [*]
Cancelado --> [*]
@enduml