@startuml
[*] --> Propuesto
Propuesto --> EnRevisión : Proponer curso
EnRevisión --> Aprobado : Revisar curso
EnRevisión --> Cancelado : Cancelar curso
Aprobado --> EnEjecución : Aprobar curso
EnEjecución --> Finalizado : Finalizar curso
EnEjecución --> Cancelado : Cancelar curso
Finalizado --> [*]
Cancelado --> [*]
@enduml